import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const formatINR = (value) => {
  const num = (value / 100).toString();
  return "Rs " + num.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
};
 
export const generatePaymentReceipt = (payment, tenant, ownerInfo) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("RENT RECEIPT", 105, 20, { align: "center" });

  doc.setFontSize(12);
  doc.text("RentEase Property Management", 105, 30, { align: "center" });

  doc.setTextColor(0, 0, 0);

  // Receipt details
  doc.setFontSize(10);
  doc.text(`Receipt No: ${payment.id.substring(0, 8).toUpperCase()}`, 20, 55);
  doc.text(
    `Date: ${new Date(payment.paidDate).toLocaleDateString("en-IN")}`,
    150,
    55
  );

  // Owner section
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.text("From:", 20, 70);
  doc.setFont(undefined, "normal");
  doc.setFontSize(10);
  doc.text(ownerInfo.name || "Property Owner", 20, 78);
  doc.text(ownerInfo.email || "", 20, 85);
  doc.text(ownerInfo.phone || "", 20, 92);

  // Tenant section
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.text("To:", 20, 110);
  doc.setFont(undefined, "normal");
  doc.setFontSize(10);
  doc.text(tenant.name, 20, 118);
  doc.text(`${tenant.propertyName} - Room ${tenant.roomNumber}`, 20, 125);
  doc.text(tenant.phone, 20, 132);
  if (tenant.email) doc.text(tenant.email, 20, 139);

  // Table (updated)
  autoTable(doc, {
  startY: 155,
  head: [["Description", "Period", "Amount"]],
  body: [
    [
      "Monthly Rent",
      new Date(payment.month + "-01").toLocaleDateString("en-IN", {
        month: "long",
        year: "numeric",
      }),
      formatINR(payment.amount)
    ],
  ],
  theme: "grid",
  headStyles: { fillColor: [37, 99, 235] },
  styles: { fontSize: 10 },
});


  // Total
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.text("Total Amount Paid:", 120, finalY);
  doc.text(`${formatINR(payment.amount)}`, 170, finalY);

  // Payment details
  doc.setFont(undefined, "normal");
  doc.setFontSize(10);
  doc.text(`Payment Method: ${payment.method}`, 20, finalY + 15);
  doc.text(
    `Payment Date: ${new Date(payment.paidDate).toLocaleDateString("en-IN")}`,
    20,
    finalY + 22
  );

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(
    "This is a computer-generated receipt and does not require a signature.",
    105,
    270,
    { align: "center" }
  );
  doc.text(
    "Generated by RentEase Property Management System",
    105,
    277,
    { align: "center" }
  );

  const filename = `Receipt_${tenant.name.replace(/\s+/g, "_")}_${
    payment.month
  }.pdf`;

  doc.save(filename);

  return { success: true, filename };
};

// ================================
//    MONTHLY REPORT (UPDATED)
// ================================

export const generateMonthlyReport = (reportData, month) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text("MONTHLY REPORT", 105, 15, { align: "center" });

  const monthName = new Date(month + "-01").toLocaleDateString("en-IN", {
    month: "long",
    year: "numeric",
  });
  doc.setFontSize(12);
  doc.text(monthName, 105, 25, { align: "center" });

  doc.setTextColor(0, 0, 0);

  // Summary
  doc.setFontSize(14);
  doc.setFont(undefined, "bold");
  doc.text("Summary", 20, 50);

  doc.setFont(undefined, "normal");
  doc.setFontSize(10);

  const summaryData = [
  ["Total Properties", reportData.totalProperties.toString()],
  ["Occupancy Rate", `${reportData.occupancyRate.toFixed(1)}%`],
  ["Expected Revenue", formatINR(reportData.expectedRevenue)],
  ["Collected Revenue", formatINR(reportData.collectedRevenue)],
  ["Collection Rate", `${reportData.collectionRate.toFixed(1)}%`],
  ["Total Expenses", formatINR(reportData.totalExpenses)],
  ["Net Income", formatINR(reportData.netIncome)],
];

autoTable(doc, {
  startY: 60,
  body: summaryData,
  theme: "plain",
  styles: { fontSize: 10, cellPadding: 3 },
  columnStyles: {
    0: { fontStyle: "bold", cellWidth: 80 },
    1: { halign: "right", cellWidth: 80 },
  },
});


  const filename = `Report_${month}.pdf`;
  doc.save(filename);

  return { success: true, filename };
};
